// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dionysus.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910175804_AddSpecificationAnalysis")]
    partial class AddSpecificationAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalysisRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationAnalysisId", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnalysisRelations");
                });

            modelBuilder.Entity("AnalysisRelationSourceStatement", b =>
                {
                    b.Property<Guid>("AnalysisRelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisStatementId")
                        .HasColumnType("uuid");

                    b.HasKey("AnalysisRelationId", "AnalysisStatementId");

                    b.HasIndex("AnalysisStatementId");

                    b.ToTable("AnalysisRelationSourceStatements");
                });

            modelBuilder.Entity("AnalysisRelationTargetStatement", b =>
                {
                    b.Property<Guid>("AnalysisRelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisStatementId")
                        .HasColumnType("uuid");

                    b.HasKey("AnalysisRelationId", "AnalysisStatementId");

                    b.HasIndex("AnalysisStatementId");

                    b.ToTable("AnalysisRelationTargetStatements");
                });

            modelBuilder.Entity("AnalysisStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBusinessContext")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SpecificationAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTopicId");

                    b.HasIndex("SpecificationAnalysisId", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnalysisStatements");
                });

            modelBuilder.Entity("AnalysisStatementSegment", b =>
                {
                    b.Property<Guid>("AnalysisStatementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TranscriptSegmentId")
                        .HasColumnType("uuid");

                    b.HasKey("AnalysisStatementId", "TranscriptSegmentId");

                    b.HasIndex("TranscriptSegmentId");

                    b.ToTable("AnalysisStatementSegments");
                });

            modelBuilder.Entity("AnalysisTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationAnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationAnalysisId", "ExternalId")
                        .IsUnique();

                    b.ToTable("AnalysisTopics");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SpecificationAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage0RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("Stage1RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("Stage2RawResponse")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEntityId")
                        .IsUnique();

                    b.ToTable("SpecificationAnalyses");
                });

            modelBuilder.Entity("SpecificationFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecificationAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTopicId");

                    b.HasIndex("SpecificationAnalysisId");

                    b.ToTable("SpecificationFunctions");
                });

            modelBuilder.Entity("SpecificationFunctionStatement", b =>
                {
                    b.Property<Guid>("SpecificationFunctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisStatementId")
                        .HasColumnType("uuid");

                    b.HasKey("SpecificationFunctionId", "AnalysisStatementId");

                    b.HasIndex("AnalysisStatementId");

                    b.ToTable("SpecificationFunctionStatements");
                });

            modelBuilder.Entity("SpecificationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecificationAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpecificationFunctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationAnalysisId");

                    b.HasIndex("SpecificationFunctionId");

                    b.ToTable("SpecificationItems");
                });

            modelBuilder.Entity("SpecificationItemStatement", b =>
                {
                    b.Property<Guid>("SpecificationItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisStatementId")
                        .HasColumnType("uuid");

                    b.HasKey("SpecificationItemId", "AnalysisStatementId");

                    b.HasIndex("AnalysisStatementId");

                    b.ToTable("SpecificationItemStatements");
                });

            modelBuilder.Entity("TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CleanedText")
                        .HasColumnType("text");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VoiceRecordingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoiceRecordingId");

                    b.ToTable("TranscriptSegments");
                });

            modelBuilder.Entity("VoiceRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AudioData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectEntityId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEntityId")
                        .IsUnique();

                    b.ToTable("VoiceRecordings");
                });

            modelBuilder.Entity("AnalysisRelation", b =>
                {
                    b.HasOne("SpecificationAnalysis", "SpecificationAnalysis")
                        .WithMany("Relations")
                        .HasForeignKey("SpecificationAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationAnalysis");
                });

            modelBuilder.Entity("AnalysisRelationSourceStatement", b =>
                {
                    b.HasOne("AnalysisRelation", "AnalysisRelation")
                        .WithMany("SourceStatementLinks")
                        .HasForeignKey("AnalysisRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalysisStatement", "AnalysisStatement")
                        .WithMany("SourceRelationLinks")
                        .HasForeignKey("AnalysisStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRelation");

                    b.Navigation("AnalysisStatement");
                });

            modelBuilder.Entity("AnalysisRelationTargetStatement", b =>
                {
                    b.HasOne("AnalysisRelation", "AnalysisRelation")
                        .WithMany("TargetStatementLinks")
                        .HasForeignKey("AnalysisRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalysisStatement", "AnalysisStatement")
                        .WithMany("TargetRelationLinks")
                        .HasForeignKey("AnalysisStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRelation");

                    b.Navigation("AnalysisStatement");
                });

            modelBuilder.Entity("AnalysisStatement", b =>
                {
                    b.HasOne("AnalysisTopic", "Topic")
                        .WithMany("Statements")
                        .HasForeignKey("AnalysisTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SpecificationAnalysis", "SpecificationAnalysis")
                        .WithMany("Statements")
                        .HasForeignKey("SpecificationAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationAnalysis");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AnalysisStatementSegment", b =>
                {
                    b.HasOne("AnalysisStatement", "AnalysisStatement")
                        .WithMany("SegmentLinks")
                        .HasForeignKey("AnalysisStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TranscriptSegment", "TranscriptSegment")
                        .WithMany()
                        .HasForeignKey("TranscriptSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisStatement");

                    b.Navigation("TranscriptSegment");
                });

            modelBuilder.Entity("AnalysisTopic", b =>
                {
                    b.HasOne("SpecificationAnalysis", "SpecificationAnalysis")
                        .WithMany("Topics")
                        .HasForeignKey("SpecificationAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationAnalysis");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecificationAnalysis", b =>
                {
                    b.HasOne("ProjectEntity", "Project")
                        .WithOne("SpecificationAnalysis")
                        .HasForeignKey("SpecificationAnalysis", "ProjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SpecificationFunction", b =>
                {
                    b.HasOne("AnalysisTopic", "Topic")
                        .WithMany("Functions")
                        .HasForeignKey("AnalysisTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SpecificationAnalysis", "SpecificationAnalysis")
                        .WithMany("Functions")
                        .HasForeignKey("SpecificationAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationAnalysis");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SpecificationFunctionStatement", b =>
                {
                    b.HasOne("AnalysisStatement", "AnalysisStatement")
                        .WithMany("FunctionLinks")
                        .HasForeignKey("AnalysisStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecificationFunction", "SpecificationFunction")
                        .WithMany("StatementLinks")
                        .HasForeignKey("SpecificationFunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisStatement");

                    b.Navigation("SpecificationFunction");
                });

            modelBuilder.Entity("SpecificationItem", b =>
                {
                    b.HasOne("SpecificationAnalysis", "SpecificationAnalysis")
                        .WithMany("Items")
                        .HasForeignKey("SpecificationAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecificationFunction", "SpecificationFunction")
                        .WithMany("Items")
                        .HasForeignKey("SpecificationFunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SpecificationAnalysis");

                    b.Navigation("SpecificationFunction");
                });

            modelBuilder.Entity("SpecificationItemStatement", b =>
                {
                    b.HasOne("AnalysisStatement", "AnalysisStatement")
                        .WithMany("ItemLinks")
                        .HasForeignKey("AnalysisStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecificationItem", "SpecificationItem")
                        .WithMany("StatementLinks")
                        .HasForeignKey("SpecificationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisStatement");

                    b.Navigation("SpecificationItem");
                });

            modelBuilder.Entity("TranscriptSegment", b =>
                {
                    b.HasOne("VoiceRecording", null)
                        .WithMany("Segments")
                        .HasForeignKey("VoiceRecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoiceRecording", b =>
                {
                    b.HasOne("ProjectEntity", null)
                        .WithMany("Recordings")
                        .HasForeignKey("ProjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalysisRelation", b =>
                {
                    b.Navigation("SourceStatementLinks");

                    b.Navigation("TargetStatementLinks");
                });

            modelBuilder.Entity("AnalysisStatement", b =>
                {
                    b.Navigation("FunctionLinks");

                    b.Navigation("ItemLinks");

                    b.Navigation("SegmentLinks");

                    b.Navigation("SourceRelationLinks");

                    b.Navigation("TargetRelationLinks");
                });

            modelBuilder.Entity("AnalysisTopic", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("ProjectEntity", b =>
                {
                    b.Navigation("Recordings");

                    b.Navigation("SpecificationAnalysis");
                });

            modelBuilder.Entity("SpecificationAnalysis", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("Items");

                    b.Navigation("Relations");

                    b.Navigation("Statements");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SpecificationFunction", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatementLinks");
                });

            modelBuilder.Entity("SpecificationItem", b =>
                {
                    b.Navigation("StatementLinks");
                });

            modelBuilder.Entity("VoiceRecording", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
