export { default as AuthPage } from './auth/AuthPage.vue'
export { default as LandingPage } from './landing/LandingPage.vue'
export { default as ProjectsPage } from './projects/ProjectsPage.vue'
export { default as ProfilePage } from './profile/ProfilePage.vue'
export { default as SpecificationPage } from './specification/SpecificationPage.vue'
